### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by bryceco** [Beakerboy/OSMBuilding#22]
I'm not sure how to use this. When I click on the Example links using Safari on Mac or iPhone all I see is a black screen.

**Comment by Beakerboy** [comment]
I made some changes to the code yesterday and introduced a regression. I need to plug in the laptop so I can see the javascript console. I wish iPhone had the developer tools.

**Comment by Beakerboy** [comment]
I just fixed a few of the examples

**Comment by bryceco** [comment]
It looks better now. There is still some weirdness with Petronas clipping. I occasionally see a little bit of a grid representing the ground and I think you should make that always appear.

**Comment by Beakerboy** [comment]
The grid is supposed to be there and 110% of the size of the base. Some of the structure have clipping where two overlapping buildings parts have very dissimilar materials. The OSMBuildings.org site had the same issue.

**Comment by bryceco** [comment]
Looks much better now. The clipping I see (on iPhone) still occurs when I zoom out.

**Comment by Beakerboy** [comment]
ahh, yes, I think the directional lighting needs to be adjusted. I'm new to both Javascript and three-js. I think when you zoom out, the light angle is too narrow, which causes the object to move into the shadows,

**Comment by Beakerboy** [comment]
All my example tenders are working.

**Comment by bryceco** [comment]
There is still clipping when zooming out. An easy solution would be to limit how for out you can zoom to ensure the building is always visible. 

My version of nethack was based on an early version of iNethack from back when Dirk was working on it, so I’m somewhat familiar with the code base. I don’t know how to access tiles on NAO though.

**Comment by bryceco** [comment]
Awesome!
